// Code generated by tools/idlgen from ../../idls/dlmm.json. DO NOT EDIT.

package lbclmm

import (
	"fmt"
	"slices"

	bin "github.com/gagliardetto/binary"
)

// DecodeBinArray reads a BinArray account from raw account data.
// The data must begin with the BinArray discriminator.
func DecodeBinArray(data []byte) (*BinArray, error) {
	if len(data) < AccountDiscriminatorLen {
		return nil, fmt.Errorf("lbclmm: %s needs at least %d bytes, got %d", "BinArray", AccountDiscriminatorLen, len(data))
	}
	if !slices.Equal(data[:AccountDiscriminatorLen], DiscriminatorBinArray[:]) {
		return nil, fmt.Errorf("lbclmm: %s discriminator mismatch", "BinArray")
	}
	want := 10136
	if len(data) < want {
		return nil, fmt.Errorf("lbclmm: %s needs %d bytes, got %d", "BinArray", want, len(data))
	}
	var out BinArray
	dec := bin.NewBorshDecoder(data[8:])
	if err := out.UnmarshalWithDecoder(dec); err != nil {
		return nil, fmt.Errorf("lbclmm: decoding %s: %w", "BinArray", err)
	}
	return &out, nil
}

// DecodeBinArrayBitmapExtension reads a BinArrayBitmapExtension account from raw account data.
// The data must begin with the BinArrayBitmapExtension discriminator.
func DecodeBinArrayBitmapExtension(data []byte) (*BinArrayBitmapExtension, error) {
	if len(data) < AccountDiscriminatorLen {
		return nil, fmt.Errorf("lbclmm: %s needs at least %d bytes, got %d", "BinArrayBitmapExtension", AccountDiscriminatorLen, len(data))
	}
	if !slices.Equal(data[:AccountDiscriminatorLen], DiscriminatorBinArrayBitmapExtension[:]) {
		return nil, fmt.Errorf("lbclmm: %s discriminator mismatch", "BinArrayBitmapExtension")
	}
	want := 1576
	if len(data) < want {
		return nil, fmt.Errorf("lbclmm: %s needs %d bytes, got %d", "BinArrayBitmapExtension", want, len(data))
	}
	var out BinArrayBitmapExtension
	dec := bin.NewBorshDecoder(data[8:])
	if err := out.UnmarshalWithDecoder(dec); err != nil {
		return nil, fmt.Errorf("lbclmm: decoding %s: %w", "BinArrayBitmapExtension", err)
	}
	return &out, nil
}

// DecodeClaimFeeOperator reads a ClaimFeeOperator account from raw account data.
// The data must begin with the ClaimFeeOperator discriminator.
func DecodeClaimFeeOperator(data []byte) (*ClaimFeeOperator, error) {
	if len(data) < AccountDiscriminatorLen {
		return nil, fmt.Errorf("lbclmm: %s needs at least %d bytes, got %d", "ClaimFeeOperator", AccountDiscriminatorLen, len(data))
	}
	if !slices.Equal(data[:AccountDiscriminatorLen], DiscriminatorClaimFeeOperator[:]) {
		return nil, fmt.Errorf("lbclmm: %s discriminator mismatch", "ClaimFeeOperator")
	}
	want := 168
	if len(data) < want {
		return nil, fmt.Errorf("lbclmm: %s needs %d bytes, got %d", "ClaimFeeOperator", want, len(data))
	}
	var out ClaimFeeOperator
	dec := bin.NewBorshDecoder(data[8:])
	if err := out.UnmarshalWithDecoder(dec); err != nil {
		return nil, fmt.Errorf("lbclmm: decoding %s: %w", "ClaimFeeOperator", err)
	}
	return &out, nil
}

// DecodeDummyZcAccount reads a DummyZcAccount account from raw account data.
// DummyZcAccount is a zero-copy account and carries no discriminator, so only its
// length is validated.
func DecodeDummyZcAccount(data []byte) (*DummyZcAccount, error) {
	want := 144
	if len(data) < want {
		return nil, fmt.Errorf("lbclmm: %s needs %d bytes, got %d", "DummyZcAccount", want, len(data))
	}
	var out DummyZcAccount
	dec := bin.NewBorshDecoder(data[0:])
	if err := out.UnmarshalWithDecoder(dec); err != nil {
		return nil, fmt.Errorf("lbclmm: decoding %s: %w", "DummyZcAccount", err)
	}
	return &out, nil
}

// DecodeLbPair reads a LbPair account from raw account data.
// The data must begin with the LbPair discriminator.
func DecodeLbPair(data []byte) (*LbPair, error) {
	if len(data) < AccountDiscriminatorLen {
		return nil, fmt.Errorf("lbclmm: %s needs at least %d bytes, got %d", "LbPair", AccountDiscriminatorLen, len(data))
	}
	if !slices.Equal(data[:AccountDiscriminatorLen], DiscriminatorLbPair[:]) {
		return nil, fmt.Errorf("lbclmm: %s discriminator mismatch", "LbPair")
	}
	want := 904
	if len(data) < want {
		return nil, fmt.Errorf("lbclmm: %s needs %d bytes, got %d", "LbPair", want, len(data))
	}
	var out LbPair
	dec := bin.NewBorshDecoder(data[8:])
	if err := out.UnmarshalWithDecoder(dec); err != nil {
		return nil, fmt.Errorf("lbclmm: decoding %s: %w", "LbPair", err)
	}
	return &out, nil
}

// DecodeLimitOrder reads a LimitOrder account from raw account data.
// The data must begin with the LimitOrder discriminator.
func DecodeLimitOrder(data []byte) (*LimitOrder, error) {
	if len(data) < AccountDiscriminatorLen {
		return nil, fmt.Errorf("lbclmm: %s needs at least %d bytes, got %d", "LimitOrder", AccountDiscriminatorLen, len(data))
	}
	if !slices.Equal(data[:AccountDiscriminatorLen], DiscriminatorLimitOrder[:]) {
		return nil, fmt.Errorf("lbclmm: %s discriminator mismatch", "LimitOrder")
	}
	want := 120
	if len(data) < want {
		return nil, fmt.Errorf("lbclmm: %s needs %d bytes, got %d", "LimitOrder", want, len(data))
	}
	var out LimitOrder
	dec := bin.NewBorshDecoder(data[8:])
	if err := out.UnmarshalWithDecoder(dec); err != nil {
		return nil, fmt.Errorf("lbclmm: decoding %s: %w", "LimitOrder", err)
	}
	return &out, nil
}

// DecodeOperator reads a Operator account from raw account data.
// The data must begin with the Operator discriminator.
func DecodeOperator(data []byte) (*Operator, error) {
	if len(data) < AccountDiscriminatorLen {
		return nil, fmt.Errorf("lbclmm: %s needs at least %d bytes, got %d", "Operator", AccountDiscriminatorLen, len(data))
	}
	if !slices.Equal(data[:AccountDiscriminatorLen], DiscriminatorOperator[:]) {
		return nil, fmt.Errorf("lbclmm: %s discriminator mismatch", "Operator")
	}
	want := 72
	if len(data) < want {
		return nil, fmt.Errorf("lbclmm: %s needs %d bytes, got %d", "Operator", want, len(data))
	}
	var out Operator
	dec := bin.NewBorshDecoder(data[8:])
	if err := out.UnmarshalWithDecoder(dec); err != nil {
		return nil, fmt.Errorf("lbclmm: decoding %s: %w", "Operator", err)
	}
	return &out, nil
}

// DecodeOracle reads a Oracle account from raw account data.
// The data must begin with the Oracle discriminator.
func DecodeOracle(data []byte) (*Oracle, error) {
	if len(data) < AccountDiscriminatorLen {
		return nil, fmt.Errorf("lbclmm: %s needs at least %d bytes, got %d", "Oracle", AccountDiscriminatorLen, len(data))
	}
	if !slices.Equal(data[:AccountDiscriminatorLen], DiscriminatorOracle[:]) {
		return nil, fmt.Errorf("lbclmm: %s discriminator mismatch", "Oracle")
	}
	want := 32
	if len(data) < want {
		return nil, fmt.Errorf("lbclmm: %s needs %d bytes, got %d", "Oracle", want, len(data))
	}
	var out Oracle
	dec := bin.NewBorshDecoder(data[8:])
	if err := out.UnmarshalWithDecoder(dec); err != nil {
		return nil, fmt.Errorf("lbclmm: decoding %s: %w", "Oracle", err)
	}
	return &out, nil
}

// DecodePositionV2 reads a PositionV2 account from raw account data.
// The data must begin with the PositionV2 discriminator.
func DecodePositionV2(data []byte) (*PositionV2, error) {
	if len(data) < AccountDiscriminatorLen {
		return nil, fmt.Errorf("lbclmm: %s needs at least %d bytes, got %d", "PositionV2", AccountDiscriminatorLen, len(data))
	}
	if !slices.Equal(data[:AccountDiscriminatorLen], DiscriminatorPositionV2[:]) {
		return nil, fmt.Errorf("lbclmm: %s discriminator mismatch", "PositionV2")
	}
	want := 8120
	if len(data) < want {
		return nil, fmt.Errorf("lbclmm: %s needs %d bytes, got %d", "PositionV2", want, len(data))
	}
	var out PositionV2
	dec := bin.NewBorshDecoder(data[8:])
	if err := out.UnmarshalWithDecoder(dec); err != nil {
		return nil, fmt.Errorf("lbclmm: decoding %s: %w", "PositionV2", err)
	}
	return &out, nil
}

// DecodePresetParameter reads a PresetParameter account from raw account data.
// The data must begin with the PresetParameter discriminator.
func DecodePresetParameter(data []byte) (*PresetParameter, error) {
	if len(data) < AccountDiscriminatorLen {
		return nil, fmt.Errorf("lbclmm: %s needs at least %d bytes, got %d", "PresetParameter", AccountDiscriminatorLen, len(data))
	}
	if !slices.Equal(data[:AccountDiscriminatorLen], DiscriminatorPresetParameter[:]) {
		return nil, fmt.Errorf("lbclmm: %s discriminator mismatch", "PresetParameter")
	}
	want := 36
	if len(data) < want {
		return nil, fmt.Errorf("lbclmm: %s needs %d bytes, got %d", "PresetParameter", want, len(data))
	}
	var out PresetParameter
	dec := bin.NewBorshDecoder(data[8:])
	if err := out.UnmarshalWithDecoder(dec); err != nil {
		return nil, fmt.Errorf("lbclmm: decoding %s: %w", "PresetParameter", err)
	}
	return &out, nil
}

// DecodePresetParameter2 reads a PresetParameter2 account from raw account data.
// The data must begin with the PresetParameter2 discriminator.
func DecodePresetParameter2(data []byte) (*PresetParameter2, error) {
	if len(data) < AccountDiscriminatorLen {
		return nil, fmt.Errorf("lbclmm: %s needs at least %d bytes, got %d", "PresetParameter2", AccountDiscriminatorLen, len(data))
	}
	if !slices.Equal(data[:AccountDiscriminatorLen], DiscriminatorPresetParameter2[:]) {
		return nil, fmt.Errorf("lbclmm: %s discriminator mismatch", "PresetParameter2")
	}
	want := 192
	if len(data) < want {
		return nil, fmt.Errorf("lbclmm: %s needs %d bytes, got %d", "PresetParameter2", want, len(data))
	}
	var out PresetParameter2
	dec := bin.NewBorshDecoder(data[8:])
	if err := out.UnmarshalWithDecoder(dec); err != nil {
		return nil, fmt.Errorf("lbclmm: decoding %s: %w", "PresetParameter2", err)
	}
	return &out, nil
}

// DecodeTokenBadge reads a TokenBadge account from raw account data.
// The data must begin with the TokenBadge discriminator.
func DecodeTokenBadge(data []byte) (*TokenBadge, error) {
	if len(data) < AccountDiscriminatorLen {
		return nil, fmt.Errorf("lbclmm: %s needs at least %d bytes, got %d", "TokenBadge", AccountDiscriminatorLen, len(data))
	}
	if !slices.Equal(data[:AccountDiscriminatorLen], DiscriminatorTokenBadge[:]) {
		return nil, fmt.Errorf("lbclmm: %s discriminator mismatch", "TokenBadge")
	}
	want := 168
	if len(data) < want {
		return nil, fmt.Errorf("lbclmm: %s needs %d bytes, got %d", "TokenBadge", want, len(data))
	}
	var out TokenBadge
	dec := bin.NewBorshDecoder(data[8:])
	if err := out.UnmarshalWithDecoder(dec); err != nil {
		return nil, fmt.Errorf("lbclmm: decoding %s: %w", "TokenBadge", err)
	}
	return &out, nil
}
