// Code generated by tools/idlgen from ../../idls/dlmm.json. DO NOT EDIT.

package lbclmm

// AccountsType mirrors the IDL enum AccountsType. The zero value is an explicit unknown sentinel so a zero-valued field cannot masquerade as the first real variant.

type AccountsType uint8

const (
	AccountsTypeInvalid                 AccountsType = iota
	AccountsTypeTransferHookX           AccountsType = 0
	AccountsTypeTransferHookY           AccountsType = 1
	AccountsTypeTransferHookReward      AccountsType = 2
	AccountsTypeTransferHookMultiReward AccountsType = 3 // carries a one-byte payload; encoded width differs per variant
	AccountsTypeTransferHookReferral    AccountsType = 4
)

// ActivationType mirrors the IDL enum ActivationType. The zero value is an explicit unknown sentinel so a zero-valued field cannot masquerade as the first real variant.

type ActivationType uint8

const (
	ActivationTypeInvalid   ActivationType = iota
	ActivationTypeSlot      ActivationType = 0
	ActivationTypeTimestamp ActivationType = 1
)

// PairStatus mirrors the IDL enum PairStatus. The zero value is an explicit unknown sentinel so a zero-valued field cannot masquerade as the first real variant.

type PairStatus uint8

const (
	PairStatusInvalid  PairStatus = iota
	PairStatusEnabled  PairStatus = 0
	PairStatusDisabled PairStatus = 1
)

// PairType mirrors the IDL enum PairType. The zero value is an explicit unknown sentinel so a zero-valued field cannot masquerade as the first real variant.

type PairType uint8

const (
	PairTypeInvalid                    PairType = iota
	PairTypePermissionless             PairType = 0
	PairTypePermission                 PairType = 1
	PairTypeCustomizablePermissionless PairType = 2
	PairTypePermissionlessV2           PairType = 3
)

// ResizeSide mirrors the IDL enum ResizeSide. The zero value is an explicit unknown sentinel so a zero-valued field cannot masquerade as the first real variant.

type ResizeSide uint8

const (
	ResizeSideInvalid ResizeSide = iota
	ResizeSideLower   ResizeSide = 0
	ResizeSideUpper   ResizeSide = 1
)

// Rounding mirrors the IDL enum Rounding. The zero value is an explicit unknown sentinel so a zero-valued field cannot masquerade as the first real variant.

type Rounding uint8

const (
	RoundingInvalid Rounding = iota
	RoundingUp      Rounding = 0
	RoundingDown    Rounding = 1
)

// StrategyType mirrors the IDL enum StrategyType. The zero value is an explicit unknown sentinel so a zero-valued field cannot masquerade as the first real variant.

type StrategyType uint8

const (
	StrategyTypeInvalid          StrategyType = iota
	StrategyTypeSpotOneSide      StrategyType = 0
	StrategyTypeCurveOneSide     StrategyType = 1
	StrategyTypeBidAskOneSide    StrategyType = 2
	StrategyTypeSpotBalanced     StrategyType = 3
	StrategyTypeCurveBalanced    StrategyType = 4
	StrategyTypeBidAskBalanced   StrategyType = 5
	StrategyTypeSpotImBalanced   StrategyType = 6
	StrategyTypeCurveImBalanced  StrategyType = 7
	StrategyTypeBidAskImBalanced StrategyType = 8
)

// TokenProgramFlags mirrors the IDL enum TokenProgramFlags. The zero value is an explicit unknown sentinel so a zero-valued field cannot masquerade as the first real variant.

type TokenProgramFlags uint8

const (
	TokenProgramFlagsInvalid          TokenProgramFlags = iota
	TokenProgramFlagsTokenProgram     TokenProgramFlags = 0
	TokenProgramFlagsTokenProgram2022 TokenProgramFlags = 1
)
