// Code generated by tools/idlgen from ../../idls/dlmm.json. DO NOT EDIT.

package lbclmm

// Option is a Borsh optional: a one-byte discriminant followed by the payload when present. It is generic so it can wrap a defined struct as well as a primitive.

type Option[T any] struct {
	Some  bool
	Value T
}

// OptionSize reports the encoded size of an Option with a payload of the given width.
func OptionSize(payload int) int { return 1 + payload }

func SomeOption[T any](v T) Option[T] { return Option[T]{Some: true, Value: v} }

func NoneOption[T any]() Option[T] { var z T; return Option[T]{Some: false, Value: z} }
