// Code generated by tools/idlgen from ../../idls/dlmm.json. DO NOT EDIT.

package lbclmm

import (
	solana "github.com/gagliardetto/solana-go"

	"github.com/pwnholic/dlmm-go/num"
)

// AddLiquidity mirrors the IDL type AddLiquidity.

type AddLiquidity struct {
	LbPair      solana.PublicKey
	From        solana.PublicKey
	Position    solana.PublicKey
	Amounts     [2]uint64
	ActiveBinId int32
}

// AddLiquidityParams mirrors the IDL type AddLiquidityParams.

type AddLiquidityParams struct {
	MinDeltaId       int32
	MaxDeltaId       int32
	X0               uint64
	Y0               uint64
	DeltaX           uint64
	DeltaY           uint64
	BitFlag          uint8
	FavorXInActiveId bool
	Padding          [16]uint8
}

// AddLiquiditySingleSidePreciseParameter mirrors the IDL type AddLiquiditySingleSidePreciseParameter.

type AddLiquiditySingleSidePreciseParameter struct {
	Bins                 []CompressedBinDepositAmount
	DecompressMultiplier uint64
}

// AddLiquiditySingleSidePreciseParameter2 mirrors the IDL type AddLiquiditySingleSidePreciseParameter2.

type AddLiquiditySingleSidePreciseParameter2 struct {
	Bins                 []CompressedBinDepositAmount
	DecompressMultiplier uint64
	MaxAmount            uint64
}

// BaseFeeParameter mirrors the IDL type BaseFeeParameter.

type BaseFeeParameter struct {
	ProtocolShare      uint16
	BaseFactor         uint16
	BaseFeePowerFactor uint8
}

// Bin mirrors the IDL type Bin.

type Bin struct {
	AmountX                       uint64
	AmountY                       uint64
	Price                         num.U128
	LiquiditySupply               num.U128
	FulfilledOrderAmountX         uint64
	FulfilledOrderAmountY         uint64
	LimitOrderFeeAskSide          uint64
	LimitOrderFeeBidSide          uint64
	FeeAmountXPerTokenStored      num.U128
	FeeAmountYPerTokenStored      num.U128
	OpenOrderAmount               uint64
	TotalProcessingOrderAmount    uint64
	ProcessedOrderRemainingAmount uint64
	OrderAge                      uint32
	LimitOrderAskSide             uint8
	Padding1                      [3]uint8
}

// BinArray mirrors the IDL type BinArray.

// DiscriminatorBinArray is the 8-byte account discriminator for BinArray.
var DiscriminatorBinArray = [8]byte{92, 142, 92, 220, 5, 148, 70, 181}

type BinArray struct {
	Index    int64
	Version  uint8
	Padding1 [7]uint8
	LbPair   solana.PublicKey
	Bins     [70]Bin
}

// BinArrayBitmapExtension mirrors the IDL type BinArrayBitmapExtension.

// DiscriminatorBinArrayBitmapExtension is the 8-byte account discriminator for BinArrayBitmapExtension.
var DiscriminatorBinArrayBitmapExtension = [8]byte{80, 111, 124, 113, 55, 237, 18, 5}

type BinArrayBitmapExtension struct {
	LbPair                 solana.PublicKey
	PositiveBinArrayBitmap [12][8]uint64
	NegativeBinArrayBitmap [12][8]uint64
}

// BinLimitOrderAmount mirrors the IDL type BinLimitOrderAmount.

type BinLimitOrderAmount struct {
	Id     int32
	Amount uint64
}

// BinLiquidityDistribution mirrors the IDL type BinLiquidityDistribution.

type BinLiquidityDistribution struct {
	BinId         int32
	DistributionX uint16
	DistributionY uint16
}

// BinLiquidityDistributionByWeight mirrors the IDL type BinLiquidityDistributionByWeight.

type BinLiquidityDistributionByWeight struct {
	BinId  int32
	Weight uint16
}

// BinLiquidityReduction mirrors the IDL type BinLiquidityReduction.

type BinLiquidityReduction struct {
	BinId       int32
	BpsToRemove uint16
}

// CancelLimitOrderEvt mirrors the IDL type CancelLimitOrderEvt.

type CancelLimitOrderEvt struct {
	LbPair     solana.PublicKey
	From       solana.PublicKey
	LimitOrder solana.PublicKey
	Amounts    [2]uint64
	ActiveId   int32
	Bins       []int32
}

// ClaimFee mirrors the IDL type ClaimFee.

type ClaimFee struct {
	LbPair   solana.PublicKey
	Position solana.PublicKey
	Owner    solana.PublicKey
	FeeX     uint64
	FeeY     uint64
}

// ClaimFee2 mirrors the IDL type ClaimFee2.

type ClaimFee2 struct {
	LbPair      solana.PublicKey
	Position    solana.PublicKey
	Owner       solana.PublicKey
	FeeX        uint64
	FeeY        uint64
	ActiveBinId int32
}

// ClaimFeeOperator mirrors the IDL type ClaimFeeOperator.

// DiscriminatorClaimFeeOperator is the 8-byte account discriminator for ClaimFeeOperator.
var DiscriminatorClaimFeeOperator = [8]byte{166, 48, 134, 86, 34, 200, 188, 150}

type ClaimFeeOperator struct {
	Operator solana.PublicKey
	Padding  [128]uint8
}

// ClaimReward mirrors the IDL type ClaimReward.

type ClaimReward struct {
	LbPair      solana.PublicKey
	Position    solana.PublicKey
	Owner       solana.PublicKey
	RewardIndex uint64
	TotalReward uint64
}

// ClaimReward2 mirrors the IDL type ClaimReward2.

type ClaimReward2 struct {
	LbPair      solana.PublicKey
	Position    solana.PublicKey
	Owner       solana.PublicKey
	RewardIndex uint64
	TotalReward uint64
	ActiveBinId int32
}

// CloseLimitOrderEvt mirrors the IDL type CloseLimitOrderEvt.

type CloseLimitOrderEvt struct {
	LbPair     solana.PublicKey
	Owner      solana.PublicKey
	LimitOrder solana.PublicKey
}

// CompositionFee mirrors the IDL type CompositionFee.

type CompositionFee struct {
	From                    solana.PublicKey
	BinId                   int16
	TokenXFeeAmount         uint64
	TokenYFeeAmount         uint64
	ProtocolTokenXFeeAmount uint64
	ProtocolTokenYFeeAmount uint64
}

// CompressedBinDepositAmount mirrors the IDL type CompressedBinDepositAmount.

type CompressedBinDepositAmount struct {
	BinId  int32
	Amount uint32
}

// CustomizableParams mirrors the IDL type CustomizableParams.

type CustomizableParams struct {
	ActiveId                int32
	BinStep                 uint16
	BaseFactor              uint16
	ActivationType          uint8
	HasAlphaVault           bool
	ActivationPoint         Option[uint64]
	CreatorPoolOnOffControl bool
	BaseFeePowerFactor      uint8
	ConcreteFunctionType    uint8
	CollectFeeMode          uint8
	Padding                 [60]uint8
}

// DecreasePositionLength mirrors the IDL type DecreasePositionLength.

type DecreasePositionLength struct {
	LbPair         solana.PublicKey
	Position       solana.PublicKey
	Owner          solana.PublicKey
	LengthToRemove uint16
	Side           uint8
}

// DummyIx mirrors the IDL type DummyIx.

type DummyIx struct {
	PairStatus       PairStatus
	PairType         PairType
	ActivationType   ActivationType
	TokenProgramFlag TokenProgramFlags
	ResizeSide       ResizeSide
	Rounding         Rounding
}

// DummyZcAccount mirrors the IDL type DummyZcAccount.

// DiscriminatorDummyZcAccount is the 8-byte account discriminator for DummyZcAccount.
var DiscriminatorDummyZcAccount = [8]byte{94, 107, 238, 80, 208, 48, 180, 8}

type DummyZcAccount struct {
	PositionBinData   PositionBinData
	LimitOrderBinData LimitOrderBinData
}

// DynamicFeeParameter mirrors the IDL type DynamicFeeParameter.

type DynamicFeeParameter struct {
	FilterPeriod             uint16
	DecayPeriod              uint16
	ReductionFactor          uint16
	VariableFeeControl       uint32
	MaxVolatilityAccumulator uint32
}

// DynamicFeeParameterUpdate mirrors the IDL type DynamicFeeParameterUpdate.

type DynamicFeeParameterUpdate struct {
	LbPair                   solana.PublicKey
	FilterPeriod             uint16
	DecayPeriod              uint16
	ReductionFactor          uint16
	VariableFeeControl       uint32
	MaxVolatilityAccumulator uint32
}

// FeeInfo mirrors the IDL type FeeInfo.

type FeeInfo struct {
	FeeXPerTokenComplete num.U128
	FeeYPerTokenComplete num.U128
	FeeXPending          uint64
	FeeYPending          uint64
}

// FeeParameterUpdate mirrors the IDL type FeeParameterUpdate.

type FeeParameterUpdate struct {
	LbPair             solana.PublicKey
	ProtocolShare      uint16
	BaseFactor         uint16
	BaseFeePowerFactor uint8
}

// FundReward mirrors the IDL type FundReward.

type FundReward struct {
	LbPair      solana.PublicKey
	Funder      solana.PublicKey
	RewardIndex uint64
	Amount      uint64
}

// GoToABin mirrors the IDL type GoToABin.

type GoToABin struct {
	LbPair    solana.PublicKey
	FromBinId int32
	ToBinId   int32
}

// IncreaseObservation mirrors the IDL type IncreaseObservation.

type IncreaseObservation struct {
	Oracle               solana.PublicKey
	NewObservationLength uint64
}

// IncreasePositionLength mirrors the IDL type IncreasePositionLength.

type IncreasePositionLength struct {
	LbPair      solana.PublicKey
	Position    solana.PublicKey
	Owner       solana.PublicKey
	LengthToAdd uint16
	Side        uint8
}

// InitPermissionPairIx mirrors the IDL type InitPermissionPairIx.

type InitPermissionPairIx struct {
	ActiveId             int32
	BinStep              uint16
	BaseFactor           uint16
	BaseFeePowerFactor   uint8
	ActivationType       uint8
	Padding0             uint16
	ConcreteFunctionType uint8
	CollectFeeMode       uint8
}

// InitPresetParametersIx mirrors the IDL type InitPresetParametersIx.

type InitPresetParametersIx struct {
	Index                    uint16
	BinStep                  uint16
	BaseFactor               uint16
	FilterPeriod             uint16
	DecayPeriod              uint16
	ReductionFactor          uint16
	VariableFeeControl       uint32
	MaxVolatilityAccumulator uint32
	ProtocolShare            uint16
	BaseFeePowerFactor       uint8
	ConcreteFunctionType     uint8
	CollectFeeMode           uint8
}

// InitializeLbPair2Params mirrors the IDL type InitializeLbPair2Params.

type InitializeLbPair2Params struct {
	ActiveId int32
	Padding  [96]uint8
}

// InitializeReward mirrors the IDL type InitializeReward.

type InitializeReward struct {
	LbPair         solana.PublicKey
	RewardMint     solana.PublicKey
	Funder         solana.PublicKey
	RewardIndex    uint64
	RewardDuration uint64
}

// LbPair mirrors the IDL type LbPair.

// DiscriminatorLbPair is the 8-byte account discriminator for LbPair.
var DiscriminatorLbPair = [8]byte{33, 11, 49, 98, 181, 101, 177, 13}

type LbPair struct {
	Parameters               StaticParameters
	VParameters              VariableParameters
	BumpSeed                 [1]uint8
	BinStepSeed              [2]uint8
	PairType                 uint8
	ActiveId                 int32
	BinStep                  uint16
	Status                   uint8
	RequireBaseFactorSeed    uint8
	BaseFactorSeed           [2]uint8
	ActivationType           uint8
	CreatorPoolOnOffControl  uint8
	TokenXMint               solana.PublicKey
	TokenYMint               solana.PublicKey
	ReserveX                 solana.PublicKey
	ReserveY                 solana.PublicKey
	ProtocolFee              ProtocolFee
	Padding1                 [32]uint8
	RewardInfos              [2]RewardInfo
	Oracle                   solana.PublicKey
	BinArrayBitmap           [16]uint64
	LastUpdatedAt            int64
	Padding2                 [32]uint8
	PreActivationSwapAddress solana.PublicKey
	BaseKey                  solana.PublicKey
	ActivationPoint          uint64
	PreActivationDuration    uint64
	Padding3                 [8]uint8
	Padding4                 uint64
	Creator                  solana.PublicKey
	TokenMintXProgramFlag    uint8
	TokenMintYProgramFlag    uint8
	Version                  uint8
	Reserved                 [21]uint8
}

// LbPairCreate mirrors the IDL type LbPairCreate.

type LbPairCreate struct {
	LbPair  solana.PublicKey
	BinStep uint16
	TokenX  solana.PublicKey
	TokenY  solana.PublicKey
}

// LimitOrder mirrors the IDL type LimitOrder.

// DiscriminatorLimitOrder is the 8-byte account discriminator for LimitOrder.
var DiscriminatorLimitOrder = [8]byte{137, 183, 212, 91, 115, 29, 141, 227}

type LimitOrder struct {
	LbPair   solana.PublicKey
	Owner    solana.PublicKey
	BinCount uint16
	Padding0 [14]uint8
	Padding1 [4]uint64
}

// LimitOrderBinData mirrors the IDL type LimitOrderBinData.

type LimitOrderBinData struct {
	Amount   uint64
	Age      uint32
	Padding0 [4]uint8
	BinId    int32
	IsAsk    uint8
	Padding1 [11]uint8
}

// LiquidityOneSideParameter mirrors the IDL type LiquidityOneSideParameter.

type LiquidityOneSideParameter struct {
	Amount               uint64
	ActiveId             int32
	MaxActiveBinSlippage int32
	BinLiquidityDist     []BinLiquidityDistributionByWeight
}

// LiquidityParameter mirrors the IDL type LiquidityParameter.

type LiquidityParameter struct {
	AmountX          uint64
	AmountY          uint64
	BinLiquidityDist []BinLiquidityDistribution
}

// LiquidityParameterByStrategy mirrors the IDL type LiquidityParameterByStrategy.

type LiquidityParameterByStrategy struct {
	AmountX              uint64
	AmountY              uint64
	ActiveId             int32
	MaxActiveBinSlippage int32
	StrategyParameters   StrategyParameters
}

// LiquidityParameterByStrategyOneSide mirrors the IDL type LiquidityParameterByStrategyOneSide.

type LiquidityParameterByStrategyOneSide struct {
	Amount               uint64
	ActiveId             int32
	MaxActiveBinSlippage int32
	StrategyParameters   StrategyParameters
}

// LiquidityParameterByWeight mirrors the IDL type LiquidityParameterByWeight.

type LiquidityParameterByWeight struct {
	AmountX              uint64
	AmountY              uint64
	ActiveId             int32
	MaxActiveBinSlippage int32
	BinLiquidityDist     []BinLiquidityDistributionByWeight
}

// Operator mirrors the IDL type Operator.

// DiscriminatorOperator is the 8-byte account discriminator for Operator.
var DiscriminatorOperator = [8]byte{219, 31, 188, 145, 69, 139, 204, 117}

type Operator struct {
	Signer     solana.PublicKey
	Permission num.U128
	Padding    [2]uint64
}

// Oracle mirrors the IDL type Oracle.

// DiscriminatorOracle is the 8-byte account discriminator for Oracle.
var DiscriminatorOracle = [8]byte{139, 194, 131, 179, 140, 179, 229, 244}

type Oracle struct {
	Idx        uint64
	ActiveSize uint64
	Length     uint64
}

// PlaceLimitOrderEvt mirrors the IDL type PlaceLimitOrderEvt.

type PlaceLimitOrderEvt struct {
	LbPair     solana.PublicKey
	Sender     solana.PublicKey
	Owner      solana.PublicKey
	LimitOrder solana.PublicKey
	ActiveId   int32
	Params     PlaceLimitOrderParams
}

// PlaceLimitOrderParams mirrors the IDL type PlaceLimitOrderParams.

type PlaceLimitOrderParams struct {
	IsAskSide   bool
	Padding     [16]uint8
	RelativeBin Option[RelativeBin]
	Bins        []BinLimitOrderAmount
}

// PositionBinData mirrors the IDL type PositionBinData.

type PositionBinData struct {
	LiquidityShare num.U128
	RewardInfo     UserRewardInfo
	FeeInfo        FeeInfo
}

// PositionClose mirrors the IDL type PositionClose.

type PositionClose struct {
	Position solana.PublicKey
	Owner    solana.PublicKey
}

// PositionCreate mirrors the IDL type PositionCreate.

type PositionCreate struct {
	LbPair   solana.PublicKey
	Position solana.PublicKey
	Owner    solana.PublicKey
}

// PositionV2 mirrors the IDL type PositionV2.

// DiscriminatorPositionV2 is the 8-byte account discriminator for PositionV2.
var DiscriminatorPositionV2 = [8]byte{117, 176, 212, 199, 245, 180, 133, 182}

type PositionV2 struct {
	LbPair                      solana.PublicKey
	Owner                       solana.PublicKey
	LiquidityShares             [70]num.U128
	RewardInfos                 [70]UserRewardInfo
	FeeInfos                    [70]FeeInfo
	LowerBinId                  int32
	UpperBinId                  int32
	LastUpdatedAt               int64
	TotalClaimedFeeXAmount      uint64
	TotalClaimedFeeYAmount      uint64
	TotalClaimedRewards         [2]uint64
	Operator                    solana.PublicKey
	LockReleasePoint            uint64
	Padding0                    uint8
	FeeOwner                    solana.PublicKey
	Version                     uint8
	PermissionlessOperationBits uint8
	Reserved                    [85]uint8
}

// PresetParameter mirrors the IDL type PresetParameter.

// DiscriminatorPresetParameter is the 8-byte account discriminator for PresetParameter.
var DiscriminatorPresetParameter = [8]byte{242, 62, 244, 34, 181, 112, 58, 170}

type PresetParameter struct {
	BinStep                  uint16
	BaseFactor               uint16
	FilterPeriod             uint16
	DecayPeriod              uint16
	ReductionFactor          uint16
	VariableFeeControl       uint32
	MaxVolatilityAccumulator uint32
	MinBinId                 int32
	MaxBinId                 int32
	ProtocolShare            uint16
}

// PresetParameter2 mirrors the IDL type PresetParameter2.

// DiscriminatorPresetParameter2 is the 8-byte account discriminator for PresetParameter2.
var DiscriminatorPresetParameter2 = [8]byte{171, 236, 148, 115, 162, 113, 222, 174}

type PresetParameter2 struct {
	BinStep                  uint16
	BaseFactor               uint16
	FilterPeriod             uint16
	DecayPeriod              uint16
	VariableFeeControl       uint32
	MaxVolatilityAccumulator uint32
	ReductionFactor          uint16
	ProtocolShare            uint16
	Index                    uint16
	BaseFeePowerFactor       uint8
	ConcreteFunctionType     uint8
	CollectFeeMode           uint8
	Padding0                 [7]uint8
	Padding1                 [19]uint64
}

// ProtocolFee mirrors the IDL type ProtocolFee.

type ProtocolFee struct {
	AmountX uint64
	AmountY uint64
}

// RebalanceLiquidityParams mirrors the IDL type RebalanceLiquidityParams.

type RebalanceLiquidityParams struct {
	ActiveId             int32
	MaxActiveBinSlippage uint16
	ShouldClaimFee       bool
	ShouldClaimReward    bool
	MinWithdrawXAmount   uint64
	MaxDepositXAmount    uint64
	MinWithdrawYAmount   uint64
	MaxDepositYAmount    uint64
	ShrinkMode           uint8
	Padding              [31]uint8
	Removes              []RemoveLiquidityParams
	Adds                 []AddLiquidityParams
}

// Rebalancing mirrors the IDL type Rebalancing.

type Rebalancing struct {
	LbPair           solana.PublicKey
	Position         solana.PublicKey
	Owner            solana.PublicKey
	ActiveBinId      int32
	XWithdrawnAmount uint64
	XAddedAmount     uint64
	YWithdrawnAmount uint64
	YAddedAmount     uint64
	XFeeAmount       uint64
	YFeeAmount       uint64
	OldMinId         int32
	OldMaxId         int32
	NewMinId         int32
	NewMaxId         int32
	Rewards          [2]uint64
}

// RelativeBin mirrors the IDL type RelativeBin.

type RelativeBin struct {
	ActiveId             int32
	MaxActiveBinSlippage int32
}

// RemainingAccountsInfo mirrors the IDL type RemainingAccountsInfo.

type RemainingAccountsInfo struct {
	Slices []RemainingAccountsSlice
}

// RemainingAccountsSlice mirrors the IDL type RemainingAccountsSlice.

type RemainingAccountsSlice struct {
	AccountsType AccountsType
	Length       uint8
}

// RemoveLiquidity mirrors the IDL type RemoveLiquidity.

type RemoveLiquidity struct {
	LbPair      solana.PublicKey
	From        solana.PublicKey
	Position    solana.PublicKey
	Amounts     [2]uint64
	ActiveBinId int32
}

// RemoveLiquidityParams mirrors the IDL type RemoveLiquidityParams.

type RemoveLiquidityParams struct {
	MinBinId Option[int32]
	MaxBinId Option[int32]
	Bps      uint16
	Padding  [16]uint8
}

// RewardInfo mirrors the IDL type RewardInfo.

type RewardInfo struct {
	Mint                                      solana.PublicKey
	Vault                                     solana.PublicKey
	Funder                                    solana.PublicKey
	RewardDuration                            uint64
	RewardDurationEnd                         uint64
	RewardRate                                num.U128
	LastUpdateTime                            uint64
	CumulativeSecondsWithEmptyLiquidityReward uint64
}

// SetPositionPermissionlessOperationBitsEvt mirrors the IDL type SetPositionPermissionlessOperationBitsEvt.

type SetPositionPermissionlessOperationBitsEvt struct {
	Position solana.PublicKey
	Owner    solana.PublicKey
	OldBits  uint8
	NewBits  uint8
}

// StaticParameters mirrors the IDL type StaticParameters.

type StaticParameters struct {
	BaseFactor               uint16
	FilterPeriod             uint16
	DecayPeriod              uint16
	ReductionFactor          uint16
	VariableFeeControl       uint32
	MaxVolatilityAccumulator uint32
	MinBinId                 int32
	MaxBinId                 int32
	ProtocolShare            uint16
	BaseFeePowerFactor       uint8
	FunctionType             uint8
	CollectFeeMode           uint8
	Padding                  [3]uint8
}

// StrategyParameters mirrors the IDL type StrategyParameters.

type StrategyParameters struct {
	MinBinId     int32
	MaxBinId     int32
	StrategyType StrategyType
	Parameteres  [64]uint8
}

// Swap mirrors the IDL type Swap.

type Swap struct {
	LbPair      solana.PublicKey
	From        solana.PublicKey
	StartBinId  int32
	EndBinId    int32
	AmountIn    uint64
	AmountOut   uint64
	SwapForY    bool
	Fee         uint64
	ProtocolFee uint64
	FeeBps      num.U128
	HostFee     uint64
}

// Swap2Evt mirrors the IDL type Swap2Evt.

type Swap2Evt struct {
	LbPair        solana.PublicKey
	From          solana.PublicKey
	StartBinId    int32
	EndBinId      int32
	SwapForY      bool
	FeeBps        num.U128
	AmountIn      uint64
	AmountLeft    uint64
	AmountOut     uint64
	MmFee         uint64
	ProtocolFee   uint64
	LimitOrderFee uint64
	HostFee       uint64
	FeesOnInput   bool
	FeesOnTokenX  bool
}

// TokenBadge mirrors the IDL type TokenBadge.

// DiscriminatorTokenBadge is the 8-byte account discriminator for TokenBadge.
var DiscriminatorTokenBadge = [8]byte{116, 219, 204, 229, 249, 116, 255, 150}

type TokenBadge struct {
	TokenMint solana.PublicKey
	Padding   [128]uint8
}

// UpdatePositionLockReleasePoint mirrors the IDL type UpdatePositionLockReleasePoint.

type UpdatePositionLockReleasePoint struct {
	Position            solana.PublicKey
	CurrentPoint        uint64
	NewLockReleasePoint uint64
	OldLockReleasePoint uint64
	Sender              solana.PublicKey
}

// UpdatePositionOperator mirrors the IDL type UpdatePositionOperator.

type UpdatePositionOperator struct {
	Position    solana.PublicKey
	OldOperator solana.PublicKey
	NewOperator solana.PublicKey
}

// UpdateRewardDuration mirrors the IDL type UpdateRewardDuration.

type UpdateRewardDuration struct {
	LbPair            solana.PublicKey
	RewardIndex       uint64
	OldRewardDuration uint64
	NewRewardDuration uint64
}

// UpdateRewardFunder mirrors the IDL type UpdateRewardFunder.

type UpdateRewardFunder struct {
	LbPair      solana.PublicKey
	RewardIndex uint64
	OldFunder   solana.PublicKey
	NewFunder   solana.PublicKey
}

// UserRewardInfo mirrors the IDL type UserRewardInfo.

type UserRewardInfo struct {
	RewardPerTokenCompletes [2]num.U128
	RewardPendings          [2]uint64
}

// VariableParameters mirrors the IDL type VariableParameters.

type VariableParameters struct {
	VolatilityAccumulator uint32
	VolatilityReference   uint32
	IndexReference        int32
	Padding               [4]uint8
	LastUpdateTimestamp   int64
	Padding1              [8]uint8
}

// WithdrawIneligibleReward mirrors the IDL type WithdrawIneligibleReward.

type WithdrawIneligibleReward struct {
	LbPair     solana.PublicKey
	RewardMint solana.PublicKey
	Amount     uint64
}
